# Data in NumPy

In [1]:
import numpy as np

In [2]:
# Create a NumPy array holding a scalar
s = np.array(5)

In [3]:
s

array(5)

In [5]:
s.shape # 0 dimensions

()

In [7]:
x = s+3

In [8]:
x

8

In [9]:
x.dtype

dtype('int32')

In [10]:
type(x)

numpy.int32

In [11]:
x.shape

()

In [12]:
# Create a vector
v = np.array([1,2,3])

In [13]:
v.shape

(3,)

In [14]:
x = v[1]

In [15]:
x

2

In [16]:
# Advanced indexing techniques
v[1:]

array([2, 3])

In [17]:
# Create 3x3 matrix
m = np.array([[1,2,3], [4,5,6], [7,8,9]])

In [18]:
m

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [19]:
m.shape

(3, 3)

In [20]:
# indexing
m[1][2]

6

In [21]:
# Create 3x3x2x1 tensor
t = np.array([[[[1], [2]], [[3], [4]], [[5], [6]]], [[[7], [8]],\
    [[9], [10]], [[11], [12]]], [[[13], [14]], [[15], [16]], [[17], [17]]]])

In [22]:
t.shape

(3, 3, 2, 1)

In [23]:
# indexing
t[2][1][1][0]

16

In [24]:
# Changing shapes
v = np.array([1,2,3,4])

In [28]:
v.shape

(4,)

In [30]:
x = v.reshape((1,4))

In [31]:
x.shape

(1, 4)

In [32]:
x = v.reshape(4,1)

In [33]:
x.shape

(4, 1)

In [34]:
# more advanced syntax
x = v[:, None]

In [35]:
x

array([[1],
       [2],
       [3],
       [4]])

In [37]:
x = v[None, :]

In [38]:
x

array([[1, 2, 3, 4]])

# Element-wise Operations in NumPy

In [39]:
# Python Way to add 5 to every item in a list

values = [1,2,3,4,5]
for i in range(len(values)):
    values[i] += 5

print(values)

[6, 7, 8, 9, 10]


In [40]:
# NumPy Way
values = [1,2,3,4,5]
values = np.array(values) + 5
print(values)

[ 6  7  8  9 10]


In [41]:
# alternatively
values = np.array([1,2,3,4,5])
values += 5
print(values)

[ 6  7  8  9 10]


In [42]:
# equivalent operations
x = np.multiply(values, 5)
y = values * 5
x == y

array([ True,  True,  True,  True,  True])

In [43]:
# Setting to zero
m = np.array([[1,2], [3, 4], [5, 6]])
print(m)

m *= 0
print(m)

[[1 2]
 [3 4]
 [5 6]]
[[0 0]
 [0 0]
 [0 0]]


In [44]:
# Squared values of a matrix back
m = np.array([[1,2,3], [4,5,6], [7,8,9]])
print(m)

m *= m
print(m)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [45]:
# Example from the video

a = np.array([[1,3], [5,7]])
print(a)

b = np.array([[2,4], [6, 8]])
print(b)

print(a+b)

[[1 3]
 [5 7]]
[[2 4]
 [6 8]]
[[ 3  7]
 [11 15]]


In [47]:
# Incompatible shapes yield an error

a = np.array([[1,3], [5, 7]])
print(a)

c = np.array([[2, 3, 6], [4, 5, 9], [1, 8, 7]])
print(c)

print(a.shape)
print(c.shape)

print(a+c)

[[1 3]
 [5 7]]
[[2 3 6]
 [4 5 9]
 [1 8 7]]
(2, 2)
(3, 3)


ValueError: operands could not be broadcast together with shapes (2,2) (3,3) 

# NumPy Matrix Multiplication

In [48]:
# Element-wise multiplication

m = np.array([[1,2,3], [4,5,6]])
print(m)

[[1 2 3]
 [4 5 6]]


In [49]:
n = m * 0.25
print(n)

[[0.25 0.5  0.75]
 [1.   1.25 1.5 ]]


In [50]:
print(m*n)

[[0.25 1.   2.25]
 [4.   6.25 9.  ]]


In [51]:
np.multiply(m, n) # equivalent to m*n


array([[0.25, 1.  , 2.25],
       [4.  , 6.25, 9.  ]])

In [52]:
# Matrix Product

a = np.array([[1,2,3,4], [5,6,7,8]])
print(a)

[[1 2 3 4]
 [5 6 7 8]]


In [53]:
a.shape

(2, 4)

In [54]:
b = np.array([[1,2,3], [4,5,6], [7,8,9], [10,11,12]])
print(b)

[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [55]:
b.shape

(4, 3)

In [56]:
c = np.matmul(a,b)
print(c)

[[ 70  80  90]
 [158 184 210]]


In [57]:
c.shape

(2, 3)

In [58]:
# Incompatible shapes
np.matmul(b, a)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 2 is different from 3)

In [59]:
# Results of `dot` and `matmul` are same if the matrices are 2-dimensional
a = np.array([[1,2], [3,4]])
print(a)

[[1 2]
 [3 4]]


In [60]:
np.dot(a, a)

array([[ 7, 10],
       [15, 22]])

In [61]:
a.dot(a)

array([[ 7, 10],
       [15, 22]])

In [62]:
np.matmul(a,a)

array([[ 7, 10],
       [15, 22]])

# Matrix Transposes

In [63]:
m = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])

In [64]:
m

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [65]:
m.T

array([[ 1,  5,  9],
       [ 2,  6, 10],
       [ 3,  7, 11],
       [ 4,  8, 12]])

In [66]:
m_t = m.T
m_t[3][1] = 200
m_t

array([[  1,   5,   9],
       [  2,   6,  10],
       [  3,   7,  11],
       [  4, 200,  12]])

In [67]:
m

array([[  1,   2,   3,   4],
       [  5,   6,   7, 200],
       [  9,  10,  11,  12]])

In [68]:
inputs = np.array([[-0.27, 0.45, 0.64, 0.31]])
inputs

array([[-0.27,  0.45,  0.64,  0.31]])

In [69]:
inputs.shape

(1, 4)

In [70]:
weights = np.array([[0.02, 0.001, -0.03, 0.036], \
                   [0.04, -0.003, 0.025, 0.009], [0.012, -0.045, 0.28, -0.067]])

In [71]:
weights

array([[ 0.02 ,  0.001, -0.03 ,  0.036],
       [ 0.04 , -0.003,  0.025,  0.009],
       [ 0.012, -0.045,  0.28 , -0.067]])

In [72]:
weights.shape

(3, 4)

In [73]:
# error
np.matmul(inputs, weights)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 4)

In [74]:
np.matmul(inputs, weights.T)

array([[-0.01299,  0.00664,  0.13494]])

In [75]:
np.matmul(weights, inputs.T)

array([[-0.01299],
       [ 0.00664],
       [ 0.13494]])

# NumPy Exam

In [88]:
inputs = [1,2,3]
x = np.array([inputs])
x
x -= x.min()
x.shape[1]

3

In [91]:
x.mean()

1.0

In [92]:
# Use the numpy library
import numpy as np


def prepare_inputs(inputs):
    # TODO: create a 2-dimensional ndarray from the given 1-dimensional list;
    #       assign it to input_array
    input_array = np.array([inputs])
    
    # TODO: find the minimum value in input_array and subtract that
    #       value from all the elements of input_array. Store the
    #       result in inputs_minus_min
    inputs_minus_min = input_array - input_array.min()

    # TODO: find the maximum value in inputs_minus_min and divide
    #       all of the values in inputs_minus_min by the maximum value.
    #       Store the results in inputs_div_max.
    inputs_div_max = inputs_minus_min / inputs_minus_min.max() 

    # return the three arrays we've created
    return input_array, inputs_minus_min, inputs_div_max
    

def multiply_inputs(m1, m2):
    # TODO: Check the shapes of the matrices m1 and m2. 
    #       m1 and m2 will be ndarray objects.
    #
    #       Return False if the shapes cannot be used for matrix
    #       multiplication. You may not use a transpose
    if m1.shape[1] != m2.shape[0] and m1.shape[0] != m2.shape[1]:
        return False

    # TODO: If you have not returned False, then calculate the matrix product
    #       of m1 and m2 and return it. Do not use a transpose,
    #       but you swap their order if necessary
    if m1.shape[1] == m2.shape[0]:
        return np.matmul(m1, m2)
    else:
        return np.matmul(m2, m1)
    

def find_mean(values):
    # TODO: Return the average of the values in the given Python list
    return np.array(values).mean()
    


input_array, inputs_minus_min, inputs_div_max = prepare_inputs([-1,2,7])
print("Input as Array: {}".format(input_array))
print("Input minus min: {}".format(inputs_minus_min))
print("Input  Array: {}".format(inputs_div_max))

print("Multiply 1:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3],[4]]))))
print("Multiply 2:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1],[2],[3]]))))
print("Multiply 3:\n{}".format(multiply_inputs(np.array([[1,2,3],[4,5,6]]), np.array([[1,2]]))))

print("Mean == {}".format(find_mean([1,3,4])))

Input as Array: [[-1  2  7]]
Input minus min: [[0 3 8]]
Input  Array: [[0.    0.375 1.   ]]
Multiply 1:
False
Multiply 2:
[[14]
 [32]]
Multiply 3:
[[ 9 12 15]]
Mean == 2.6666666666666665
